version: '2'
services:
    cos482-mysql:
        container_name: cos482-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/cos482/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=cos482
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
